trigger:
  branches:
    include:
      - master  # or your specific branch

pool:
  name: 'Default'  # Replace with your self-hosted pool name

steps:
- script: |
    curl -sL https://releases.hashicorp.com/terraform/1.5.2/terraform_1.5.2_linux_amd64.zip -o terraform.zip
    sudo apt-get install unzip -y
    unzip terraform.zip
    sudo mv terraform /usr/local/bin/
    terraform -v  # Verify installation
  displayName: 'Install Terraform'

- script: |
    terraform init
  displayName: 'Initialize Terraform'

- script: |
    terraform validate
  displayName: 'Validate Terraform'

- script: |
    terraform plan -out=tfplan
  displayName: 'Terraform Plan'

- script: |
    terraform apply -auto-approve tfplan
  displayName: 'Terraform Apply'
